import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import HeaderBar from '@/components/header/HeaderBar';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable}`}>
                <div className="container pt-4 mx-auto px-4 max-w-6xl">
                    <h1 className="text-3xl font-bold mb-6">
                        Lunch Recommender
                    </h1>

                    <HeaderBar />

                    {children}
                </div>
            </body>
        </html>
    );
}
